<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Mon, 24 Jun 2024 18:26:14 GMT</lastBuildDate>
    <item>
      <title>运行失败，抱歉，出现错误。发送图像时出错</title>
      <link>https://community.openai.com/t/run-failed-sorry-something-went-wrong-error-while-sending-an-image/775989?page=3#post_56</link>
      <description><![CDATA[也收到此错误，这影响了我的生产应用程序。已提交支持单。如果您遇到此问题，请也提交一张单子，并粘贴此代码。这是我在 Python 中创建的最小示例，用于重现错误：
from openai import OpenAI
import time

client = OpenAI()
your_image_path = &quot;my_file.png&quot;

# 创建测试助手
assistant = client.beta.assistants.create(
name=&quot;测试助手&quot;,
description=&quot;你是一个有用的助手。&quot;,
model=&quot;gpt-4o&quot;
)

# 创建文件对象
file = client.files.create(
file=open(your_image_path, &quot;rb&quot;),
purpose=&quot;vision&quot;
)

# 创建带有消息的线程
thread = client.beta.threads.create(
messages=[
{
&quot;role&quot;: &quot;user&quot;,
&quot;content&quot;: [
{
&quot;type&quot;: &quot;text&quot;,
&quot;text&quot;: &quot;描述此图像。&quot;
},
{
&quot;type&quot;: &quot;image_file&quot;,
&quot;image_file&quot;: {&quot;file_id&quot;: file.id}
},
],
}
]
)

run = client.beta.threads.runs.create_and_poll(
thread_id=thread.id,
assistant_id=assistant.id
)

while run.status in [&#39;queued&#39;, &#39;in_progress&#39;, &#39;requires_action&#39;]:
print(run.status)
time.sleep(1)
else:
print(f&quot;run.status: {run}&quot;) # 这将返回服务器错误
]]></description>
      <guid>https://community.openai.com/t/run-failed-sorry-something-went-wrong-error-while-sending-an-image/775989?page=3#post_56</guid>
      <pubDate>Mon, 24 Jun 2024 18:25:13 GMT</pubDate>
    </item>
    <item>
      <title>功能请求：基于文件夹的 ChatGPT 对话组织</title>
      <link>https://community.openai.com/t/feature-request-folder-based-organization-for-chatgpt-conversations/672115?page=2#post_44</link>
      <description><![CDATA[有浏览器扩展程序可以将文件夹添加到 ChatGPT。我无法在这里分享链接，但你可以自己谷歌搜索。]]></description>
      <guid>https://community.openai.com/t/feature-request-folder-based-organization-for-chatgpt-conversations/672115?page=2#post_44</guid>
      <pubDate>Mon, 24 Jun 2024 18:24:41 GMT</pubDate>
    </item>
    <item>
      <title>您已达到使用限制。请稍后重试</title>
      <link>https://community.openai.com/t/youve-hit-your-usage-limit-please-try-again-later/835602#post_16</link>
      <description><![CDATA[我也遇到了同样的事情。]]></description>
      <guid>https://community.openai.com/t/youve-hit-your-usage-limit-please-try-again-later/835602#post_16</guid>
      <pubDate>Mon, 24 Jun 2024 18:23:19 GMT</pubDate>
    </item>
    <item>
      <title>移动应用程序滚动故障</title>
      <link>https://community.openai.com/t/mobile-app-scrolling-glitching/564237#post_15</link>
      <description><![CDATA[事实上，这个问题已经拖了好几个月，而且影响如此之大，基本上影响到了每一个 iPhone 和 iPad 用户，这让我很想知道他们的 UI 团队在做什么？我是不是漏掉了什么？这不可能用一行代码就能解决……这是怎么回事？]]></description>
      <guid>https://community.openai.com/t/mobile-app-scrolling-glitching/564237#post_15</guid>
      <pubDate>Mon, 24 Jun 2024 18:22:39 GMT</pubDate>
    </item>
    <item>
      <title>Vision 无法与 OpenAI NuGet 配合使用</title>
      <link>https://community.openai.com/t/vision-not-working-with-openai-nuget/832719#post_4</link>
      <description><![CDATA[api 不稳定，可能你的代码没什么问题




运行失败，抱歉，出错了。发送图像时出错 错误


以防有用，这是我在支持聊天中起草的消息，如果其他人发送类似的请求，可能会提高知名度：
自 6 月 20 日星期四以来，助手 API 与图像输入和输出相关的中断严重。请参阅此处的线程：运行失败，抱歉，出现错误。发送图像时出错 
您可以通过创建新助手、启用代码解释器并请求示例 matplotlib 可视化，轻松地在 Assistants Playground 中重现此问题……

]]></description>
      <guid>https://community.openai.com/t/vision-not-working-with-openai-nuget/832719#post_4</guid>
      <pubDate>Mon, 24 Jun 2024 18:20:25 GMT</pubDate>
    </item>
    <item>
      <title>让 GPT-4o 分析包含大量文本的文档</title>
      <link>https://community.openai.com/t/getting-gpt-4o-to-analyse-docs-with-large-blocks-of-text/837785#post_3</link>
      <description><![CDATA[非常感谢。我会研究一下（我对 Python 不是很熟悉）所以这看起来是不是我的方法不对？ initial_context 将是大量文本： import sys
import os
from openai import OpenAI
client = OpenAI()
class OpenAIHelper:
def init(self):
self.api_key = os.getenv(‘OPENAI_API_KEY’)
client.api_key = self.api_key
def query_with_context(self, initial_context, prompt):
completion = client.chat.completions.create(
model=“gpt-4o”,
messages=[
{“role”: “system”, “content”: “您是一位知识渊博的助手。请根据提供的文本回答问题。”},
{“role”: “user”, “content”: f&quot;给定先前的文本：{initial_context}\n{prompt}&quot;&gt;
],
temperature=0.5
)
return finish.choices[0].message[‘content’]
def analyze_text(self, text, prompts):
results = {&gt;
for prompt_name, prompt_text in prompts.items():
results[prompt_name] = self.query_with_context(text, prompt_text)
return results]]></description>
      <guid>https://community.openai.com/t/getting-gpt-4o-to-analyse-docs-with-large-blocks-of-text/837785#post_3</guid>
      <pubDate>Mon, 24 Jun 2024 18:19:39 GMT</pubDate>
    </item>
    <item>
      <title>带有本地向量存储的助手 API</title>
      <link>https://community.openai.com/t/assistants-api-with-local-vector-store/837615#post_2</link>
      <description><![CDATA[这怎么可能？如果你不将其添加到说明或线程中，助手将不知道你的数据]]></description>
      <guid>https://community.openai.com/t/assistants-api-with-local-vector-store/837615#post_2</guid>
      <pubDate>Mon, 24 Jun 2024 18:18:26 GMT</pubDate>
    </item>
    <item>
      <title>列出并删除所有线程</title>
      <link>https://community.openai.com/t/list-and-delete-all-threads/505823#post_5</link>
      <description><![CDATA[这仍然有效，但是我发现我还必须添加我的项目密钥。您可以在个人资料设置和检查器中找到它。]]></description>
      <guid>https://community.openai.com/t/list-and-delete-all-threads/505823#post_5</guid>
      <pubDate>Mon, 24 Jun 2024 18:12:11 GMT</pubDate>
    </item>
    <item>
      <title>文件搜索忽略“最大结果数”</title>
      <link>https://community.openai.com/t/file-search-is-ignores-the-max-num-results/826833#post_4</link>
      <description><![CDATA[有没有办法使用 python sdk 以编程方式更改所有这些设置？]]></description>
      <guid>https://community.openai.com/t/file-search-is-ignores-the-max-num-results/826833#post_4</guid>
      <pubDate>Mon, 24 Jun 2024 18:09:26 GMT</pubDate>
    </item>
    <item>
      <title>无法将文件上传至 Assistant V2 Api</title>
      <link>https://community.openai.com/t/cannot-upload-file-to-assistant-v2-api/807698#post_3</link>
      <description><![CDATA[您可以使用 http api 上传文件，这样更简单，而且您不需要依赖该库]]></description>
      <guid>https://community.openai.com/t/cannot-upload-file-to-assistant-v2-api/807698#post_3</guid>
      <pubDate>Mon, 24 Jun 2024 18:09:13 GMT</pubDate>
    </item>
    <item>
      <title>缺少插件访问权限 - 没有测试版选项 - Plus 用户</title>
      <link>https://community.openai.com/t/missing-plugin-access-no-beta-option-plus-user/837823#post_3</link>
      <description><![CDATA[完美的回应，我以为我疯了！谢谢！]]></description>
      <guid>https://community.openai.com/t/missing-plugin-access-no-beta-option-plus-user/837823#post_3</guid>
      <pubDate>Mon, 24 Jun 2024 18:08:08 GMT</pubDate>
    </item>
    <item>
      <title>运行失败，抱歉，出现错误。发送图像时出错</title>
      <link>https://community.openai.com/t/run-failed-sorry-something-went-wrong-error-while-sending-an-image/775989?page=3#post_55</link>
      <description><![CDATA[如果有用的话，这是我在支持聊天中起草的消息，也许如果其他人发送类似的请求，它会提升可见性：
自 6 月 20 日星期四以来，Assistant API 中与图像输入和输出相关的中断严重。请参阅此处的线程：运行失败，抱歉，出错了。发送图像时出错
您可以通过创建新助手、启用代码解释器并请求示例 matplotlib 可视化，轻松地在 Assistants Playground 中重现。每次运行都会失败。这模仿了 Assistants API 中看到的行为，任何生成图像的运行都会失败。是否可以从人类那里得到一些反馈？这是一次影响生产应用程序的重大中断，我们尚未收到任何反馈。]]></description>
      <guid>https://community.openai.com/t/run-failed-sorry-something-went-wrong-error-while-sending-an-image/775989?page=3#post_55</guid>
      <pubDate>Mon, 24 Jun 2024 18:04:46 GMT</pubDate>
    </item>
    <item>
      <title>让 GPT-4o 分析包含大量文本的文档</title>
      <link>https://community.openai.com/t/getting-gpt-4o-to-analyse-docs-with-large-blocks-of-text/837785#post_2</link>
      <description><![CDATA[是的，您可以使用 create_thread_run 并上传文件一次并链接到每个线程，然后针对您配置的助手运行线程]]></description>
      <guid>https://community.openai.com/t/getting-gpt-4o-to-analyse-docs-with-large-blocks-of-text/837785#post_2</guid>
      <pubDate>Mon, 24 Jun 2024 18:04:18 GMT</pubDate>
    </item>
    <item>
      <title>运行失败，抱歉，出现错误。发送图像时出错</title>
      <link>https://community.openai.com/t/run-failed-sorry-something-went-wrong-error-while-sending-an-image/775989?page=3#post_54</link>
      <description><![CDATA[确认我的助手 Playground 和使用助手 API 也出现了同样的情况。有人收到 OpenAI 的反馈吗？显然他们没有查看论坛……]]></description>
      <guid>https://community.openai.com/t/run-failed-sorry-something-went-wrong-error-while-sending-an-image/775989?page=3#post_54</guid>
      <pubDate>Mon, 24 Jun 2024 17:58:17 GMT</pubDate>
    </item>
    <item>
      <title>缺少插件访问权限 - 没有测试版选项 - Plus 用户</title>
      <link>https://community.openai.com/t/missing-plugin-access-no-beta-option-plus-user/837823#post_2</link>
      <description><![CDATA[嗨。
我得看看现在是哪一年了。ChatGPT 插件，顾名思义，已经停用并永久关闭。替代的是“GPTs”。
您是想讨论其他事情吗？]]></description>
      <guid>https://community.openai.com/t/missing-plugin-access-no-beta-option-plus-user/837823#post_2</guid>
      <pubDate>Mon, 24 Jun 2024 17:54:23 GMT</pubDate>
    </item>
    </channel>
</rss>