<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Mon, 15 Jul 2024 03:24:54 GMT</lastBuildDate>
    <item>
      <title>问题很快就解决了。👉 我的 AI 聊天机器人说我已经超出了配额，但我的 OpenAI 帐户还有很多积分</title>
      <link>https://community.openai.com/t/issues-quickly-my-ai-chatbot-says-i-have-exceeded-my-quota-yet-my-openai-account-has-plenty-of-credits/638627#post_10</link>
      <description><![CDATA[问题似乎已经自行解决。]]></description>
      <guid>https://community.openai.com/t/issues-quickly-my-ai-chatbot-says-i-have-exceeded-my-quota-yet-my-openai-account-has-plenty-of-credits/638627#post_10</guid>
      <pubDate>Mon, 15 Jul 2024 03:20:43 GMT</pubDate>
    </item>
    <item>
      <title>代码解释器的令牌溢出</title>
      <link>https://community.openai.com/t/token-overflow-with-code-interpreter/866356#post_1</link>
      <description><![CDATA[您好，我一直在使用带有助手 API 和 gpt4o 的代码解释器，遇到了一个问题。当输入达到一定数量的标记时，ChatGPT 会大幅添加不存在的标记。
工作流程如下：
1.- 我使用助手创建图表，其中包含有关带有虚假数据的 CSV 文件的说明，然后我在提示中提供它们，以便能够基于这些数据进行查询。
2.- 我提供了一定数量的信息，即 85 行，共计 19239 个标记，包括输出和说明，在这种情况下，我说“用这些数据给我做一个图表”，说的是有关一个主题。
这是一个简单的打印，用于计算日志数量（85）。

完成、提示和总令牌数量（4108、15131 和 19239）。它低于上下文长度。

助手运行良好并生成图表，但如果我再添加一条数据，我就会得到这个：
这只是一个简单的日志。

如何查看令牌使用量急剧上升，但为什么呢？（28494、127829 和 156778 个令牌）。这是我们可以预期的更高值。

如果我错了或者发生了一些我不该发生的事情知道的话请告诉我。
谢谢。]]></description>
      <guid>https://community.openai.com/t/token-overflow-with-code-interpreter/866356#post_1</guid>
      <pubDate>Mon, 15 Jul 2024 02:51:08 GMT</pubDate>
    </item>
    <item>
      <title>我住在威尔士，但说英语。ChatGPT 感到困惑</title>
      <link>https://community.openai.com/t/i-live-in-wales-but-speak-english-chatgpt-is-confused/807620?page=2#post_24</link>
      <description><![CDATA[我住在巴西，我也遇到过这种情况。我的应用是英文的，我在偏好设置中将语言设置为英语，但有时我说英语，它却用葡萄牙语书写。所以我想，这纯粹是地理问题。幸运的是，我懂葡萄牙语。]]></description>
      <guid>https://community.openai.com/t/i-live-in-wales-but-speak-english-chatgpt-is-confused/807620?page=2#post_24</guid>
      <pubDate>Mon, 15 Jul 2024 02:33:32 GMT</pubDate>
    </item>
    <item>
      <title>文件创建（Excel 电子表格）</title>
      <link>https://community.openai.com/t/file-creation-excel-spreadsheet/864609#post_4</link>
      <description><![CDATA[就在我回复你们之前再次测试了一下，它又可以正常工作了……但下次遇到问题时，我会分享一些截图。感谢您抽出时间回复。非常感谢！]]></description>
      <guid>https://community.openai.com/t/file-creation-excel-spreadsheet/864609#post_4</guid>
      <pubDate>Mon, 15 Jul 2024 02:31:30 GMT</pubDate>
    </item>
    <item>
      <title>当我用数字回复时，状态代码 400 语音流问题</title>
      <link>https://community.openai.com/t/status-code-400-voice-flow-issue-when-i-reply-with-numbers/866326#post_1</link>
      <description><![CDATA[我正在使用语音流，并通过 replit 连接并创建了一个聊天机器人。对话世界很好。但是当我添加数字时它不起作用并回复此错误？
API 调用错误 - {“status”:400, “data”:
{“VF_STATUS_CODE”:400, “VF_HEADERS”:(“alt-svc”:“h3=”:443&quot;; ma=2592000,h3-29=“:443”; ma=2592000&quot;, “connection”:“close”, “content-length”:“167”, “content-type”:“text/html; charset=utf-8”, “date”: “Mon, 15 Jul 2024 01:38:12
GMT”, “server”:“Werkzeug/3.0.1 Python/3.10.14”, “strict-transport-security”:“max-age=63072000; includeSubDomains”, “via”:“1.1 google”}}&gt;
无法创建生成响应！
我的 replit 函数代码如下；
import json
import os
def create_assistant(client):
assistant_file_path = ‘assistant.json’
if os.path.exists(assistant_file_path):
with open(assistant_file_path, ‘r’) as file:
assistant_data = json.load(file)
assistant_id = assistant_data[‘assistant_id’]
print(“Loaded already established assistant ID.”)
else:
file = client.files.create(file=open(“knowledge.docx”, “rb”),
purpose=‘assistants’)
assistant = client.beta.assistants.create(instructions=&quot;&quot;&quot;
助手 Investment Insight 已被设计为向潜在客户提供有关澳大利亚房地产投资的信息。帮助做出明智的决定。

&quot;&quot;&quot;,
model=&quot;gpt-4-tubro&quot;,
tools=[{
&quot;type&quot;: &quot;retrieval&quot;
}],
file_ids=[file.id])

with open(assistant_file_path, &#39;w&#39;) as file:
json.dump({&#39;assistant_id&#39;: assistant.id}, file)
print(&quot;创建了一个新的助手并保存了 ID。&quot;)

assistant_id = assistant.id

return assistant_id
任何帮助，我很乐意付钱。尽快解决这个问题会很棒。]]></description>
      <guid>https://community.openai.com/t/status-code-400-voice-flow-issue-when-i-reply-with-numbers/866326#post_1</guid>
      <pubDate>Mon, 15 Jul 2024 02:06:25 GMT</pubDate>
    </item>
    <item>
      <title>配额不足（尽管有剩余信用且远低于限额）</title>
      <link>https://community.openai.com/t/insufficient-quota-despite-having-credits-left-and-being-far-below-the-limit/339290#post_16</link>
      <description><![CDATA[同样的问题……论坛上到处都是这个问题，但我找不到除了增加信用余额或启用自动充值以外的解决方案——我已经这样做了，但仍然收到消息。但我的余额从来没有达到 0.00，甚至还差得很远。]]></description>
      <guid>https://community.openai.com/t/insufficient-quota-despite-having-credits-left-and-being-far-below-the-limit/339290#post_16</guid>
      <pubDate>Mon, 15 Jul 2024 01:39:07 GMT</pubDate>
    </item>
    <item>
      <title>错误代码：429，余额不足</title>
      <link>https://community.openai.com/t/error-code-429-while-having-sufficient-balance/711285#post_3</link>
      <description><![CDATA[嘿 @coffeeboy7411 所以你说你最初没有自动充值或信用余额？我收到此错误，我两者都有……]]></description>
      <guid>https://community.openai.com/t/error-code-429-while-having-sufficient-balance/711285#post_3</guid>
      <pubDate>Mon, 15 Jul 2024 01:37:39 GMT</pubDate>
    </item>
    <item>
      <title>问题很快就解决了。👉 我的 AI 聊天机器人说我已经超出了配额，但我的 OpenAI 帐户还有很多积分</title>
      <link>https://community.openai.com/t/issues-quickly-my-ai-chatbot-says-i-have-exceeded-my-quota-yet-my-openai-account-has-plenty-of-credits/638627#post_9</link>
      <description><![CDATA[你找到解决办法了吗？]]></description>
      <guid>https://community.openai.com/t/issues-quickly-my-ai-chatbot-says-i-have-exceeded-my-quota-yet-my-openai-account-has-plenty-of-credits/638627#post_9</guid>
      <pubDate>Mon, 15 Jul 2024 01:36:15 GMT</pubDate>
    </item>
    <item>
      <title>OpenAI API 功能隐藏成本？</title>
      <link>https://community.openai.com/t/openai-api-hidden-costs-to-functions/866313#post_1</link>
      <description><![CDATA[大家好，创建助手需要花钱吗？创建矢量存储？上传文件？
我不这么认为，但想确认一下。非常感谢！]]></description>
      <guid>https://community.openai.com/t/openai-api-hidden-costs-to-functions/866313#post_1</guid>
      <pubDate>Mon, 15 Jul 2024 01:35:35 GMT</pubDate>
    </item>
    <item>
      <title>RateLimitError：需要帮助解决配额问题</title>
      <link>https://community.openai.com/t/ratelimiterror-need-assistance-resolving-quota-issue/525811#post_13</link>
      <description><![CDATA[你在这里得到过解决方案吗？]]></description>
      <guid>https://community.openai.com/t/ratelimiterror-need-assistance-resolving-quota-issue/525811#post_13</guid>
      <pubDate>Mon, 15 Jul 2024 01:35:28 GMT</pubDate>
    </item>
    <item>
      <title>429 当仅使用 35% 的配额时出现最大配额问题</title>
      <link>https://community.openai.com/t/429-max-quota-issue-when-only-35-of-quota-is-used/698690#post_8</link>
      <description><![CDATA[你在这里找到解决方案了吗？我最近也遇到了这个问题，但还是不明白为什么……]]></description>
      <guid>https://community.openai.com/t/429-max-quota-issue-when-only-35-of-quota-is-used/698690#post_8</guid>
      <pubDate>Mon, 15 Jul 2024 01:34:09 GMT</pubDate>
    </item>
    <item>
      <title>无法将多种文件类型上传到矢量存储</title>
      <link>https://community.openai.com/t/cannot-upload-several-file-types-to-vector-store/861547#post_15</link>
      <description><![CDATA[我一直怀疑问题与 mimetype 标头在某处出现问题有关。要排除 ruby​​ 库作为原因，请尝试使用 curl，如以下 shell 脚本所示：
#!/bin/sh
if [ &quot;${OPENAI_API_KEY}&quot; = &quot;&quot; ];然后
echo “缺少 OPENAI_API_KEY env”
exit
fi

CONTENT_TYPE=&quot;text/plain&quot;
FILE_STORE_ID=&quot;file-w5ZxKuQYi5lSsOnhKLto7tgo&quot;
VECTOR_STORE_ID=&quot;vs_BGZTsHutIG4ncQkAjQYo7pJm&quot;

curl https://api.openai.com/v1/vector_stores/${VECTOR_STORE_ID}/files \
-H “授权：持有者 ${OPENAI_API_KEY}” \
-H “内容类型：${CONTENT_TYPE}” \
-H “OpenAI-Beta：assistants=v2” \
-d “{
\&quot;file_id\&quot;: ${FILE_STORE_ID}
}”


更改FILE_STORE_ID 为“.rb”或“.txt”文件 ID。我认为内容类型“text/plain”应该是一个很好的通用 mimetype 选择。如果这有效，那么我可以为您提供补救措施，但您可能不会喜欢它。]]></description>
      <guid>https://community.openai.com/t/cannot-upload-several-file-types-to-vector-store/861547#post_15</guid>
      <pubDate>Mon, 15 Jul 2024 01:23:14 GMT</pubDate>
    </item>
    <item>
      <title>无法将多种文件类型上传到矢量存储</title>
      <link>https://community.openai.com/t/cannot-upload-several-file-types-to-vector-store/861547#post_14</link>
      <description><![CDATA[这些是文件。 没有什么复杂的内容。
https://drive.google.com/drive/folders/1jOlwaWBwhgv9TwK3JWGY48cKtkeVy7N-?usp=sharing]]></description>
      <guid>https://community.openai.com/t/cannot-upload-several-file-types-to-vector-store/861547#post_14</guid>
      <pubDate>Mon, 15 Jul 2024 01:07:24 GMT</pubDate>
    </item>
    <item>
      <title>如何处理单个 API 请求中的响应限制？</title>
      <link>https://community.openai.com/t/how-you-deal-with-response-limit-in-a-single-api-request/500506#post_4</link>
      <description><![CDATA[我的自定义 API 返回了大量文本，最终我自己也遇到了这个限制。在失败的返回中，数据大小约为 109k 和 21k 个标记。我相信上面的发帖人是正确的，限制是 100k 字节。
我今天要进行一些测试来确定这是否正确。]]></description>
      <guid>https://community.openai.com/t/how-you-deal-with-response-limit-in-a-single-api-request/500506#post_4</guid>
      <pubDate>Mon, 15 Jul 2024 01:06:46 GMT</pubDate>
    </item>
    <item>
      <title>无法将多种文件类型上传到矢量存储</title>
      <link>https://community.openai.com/t/cannot-upload-several-file-types-to-vector-store/861547#post_13</link>
      <description><![CDATA[blah.txt 以完全相同的方式失败：


 file = client.files.upload(
参数：{
file：path_to_upload，
purpose：&quot;assistants&quot;
}
)

{&quot;object&quot;=&gt;&quot;file&quot;, &quot;id&quot;=&gt;&quot;file-cr2IqoYc5TKLAy9g3tXSsLn5&quot;, &quot;purpose&quot;=&gt;&quot;assistants&quot;, &quot;filename&quot;=&gt;&quot;blah.txt&quot;, &quot;bytes&quot;=&gt;48, &quot;created_at&quot;=&gt;1721005143, &quot;status&quot;=&gt;&quot;processed&quot;, &quot;status_details&quot;=&gt;nil}

 response = client.vector_store_files.create(
vector_store_id: vector_store[&#39;id&#39;],
parameters: {
file_id: file[&#39;id&#39;]
}
)
{&quot;id&quot;=&gt;&quot;file-cr2IqoYc5TKLAy9g3tXSsLn5&quot;, &quot;object&quot;=&gt;&quot;vector_store.file&quot;, &quot;usage_bytes&quot;=&gt;0, &quot;created_at&quot;=&gt;1721005143, &quot;vector_store_id&quot;=&gt;&quot;vs_BGZTsHutIG4ncQkAjQYo7pJm&quot;, “status”=&gt;“in_progress”, “last_error”=&gt;nil, “chunking_strategy”=&gt;{“type”=&gt;“static”, “static”=&gt;{“max_chunk_size_tokens”=&gt;800, “chunk_overlap_tokens”=&gt;400}}}

client.vector_store_files.list(vector_store_id: vector_store[&#39;id&#39;])

{“object”=&gt;“list”,
“data”=&gt;
[{&quot;id&quot;=&gt;&quot;file-cr2IqoYc5TKLAy9g3tXSsLn5&quot;,
&quot;object&quot;=&gt;&quot;vector_store.file&quot;,
&quot;usage_bytes&quot;=&gt;0,
&quot;created_at&quot;=&gt;1721005143,
&quot;vector_store_id&quot;=&gt;&quot;vs_BGZTsHutIG4ncQkAjQYo7pJm&quot;,
&quot;status&quot;=&gt;&quot;failed&quot;,
&quot;last_error&quot;=&gt;{&quot;code&quot;=&gt;&quot;unsupported_file&quot;, &quot;message&quot;=&gt;&quot;不支持该文件类型。&quot;},
&quot;chunking_strategy&quot;=&gt;{&quot;type&quot;=&gt;&quot;static&quot;, &quot;static&quot;=&gt;{&quot;max_chunk_size_tokens&quot;=&gt;800, &quot;chunk_overlap_tokens&quot;=&gt;400}}},
{&quot;id&quot;=&gt;&quot;file-w5ZxKuQYi5lSsOnhKLto7tgo&quot;,
&quot;object&quot;=&gt;&quot;vector_store.file&quot;,
&quot;usage_bytes&quot;=&gt;0,
&quot;created_at&quot;=&gt;1720957235,
&quot;vector_store_id&quot;=&gt;&quot;vs_BGZTsHutIG4ncQkAjQYo7pJm&quot;,
&quot;status&quot;=&gt;&quot;failed&quot;,
&quot;last_error&quot;=&gt;{&quot;code&quot;=&gt;&quot;unsupported_file&quot;, &quot;message&quot;=&gt;&quot;不支持该文件类型。&quot;},
&quot;chunking_strategy&quot;=&gt;{&quot;type&quot;=&gt;&quot;static&quot;, “static”=&gt;{“max_chunk_size_tokens”=&gt;800，“chunk_overlap_tokens”=&gt;400}}}],
“first_id”=&gt;“file-cr2IqoYc5TKLAy9g3tXSsLn5”,
“last_id”=&gt;“file-w5ZxKuQYi5lSsOnhKLto7tgo”,
“has_more”=&gt;false}
]]></description>
      <guid>https://community.openai.com/t/cannot-upload-several-file-types-to-vector-store/861547#post_13</guid>
      <pubDate>Mon, 15 Jul 2024 01:02:11 GMT</pubDate>
    </item>
    </channel>
</rss>